---
name: Semantic Release

on: # yamllint disable-line
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      new_release_published: ${{ steps.release.outputs.new_release_published }}
      new_release_version: ${{ steps.release.outputs.new_release_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.2.3 # https://github.com/cycjimmy/semantic-release-action/issues/243
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Trigger Galaxy release
    needs: semantic-release
    if: needs.semantic-release.outputs.new_release_published == 'true'
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.semantic-release.outputs.new_release_version }}
    secrets: inherit
